### ISSUE TITLE
 5zig reborn Forge support

### ISSUE THREAD

**Issue by apptester235** [5zig-reborn/The-5zig-Mod#10]
I have read the 3.13.0 change log and so you have said that there isn't yet support for forge but is support for forge going to be implemented for all versions in the future releases. I have seen that you have updated the mod up to 1.15.2, which is great and so I just wanted to see the road map or features which are going to be implemented in future releases?
Thank you for the work that you have been doing.

**Comment by RoccoDev** [comment]
We support Forge for 1.8.9 and 1.12.2.
You can follow the development of Forge support for 1.14+ in #4.

**Comment by apptester235** [comment]
Oh thank you for making this clear, hopefully there is going to be upcoming support for forge 1.15.2 in the future.
