### ISSUE TITLE
Update the mod to 1.16

### ISSUE THREAD

**Issue by KennuGaming** [5zig-reborn/The-5zig-Mod#107]
I would really want a 1.16 version so i could afk in servers without the server closing.

**Comment by SKBotNL** [comment]
Yeah, 1.16 is out for a little while now and i just want 5zig. It's so irritating

**Comment by RoccoDev** [comment]
You can follow 1.16 updates in the 1.16 branch. Alpha builds are available [here](https://github.com/5zig-reborn/deployments/tree/1.16).
