### ISSUE TITLE
[1.8.9] [Mod Compat] [Bug] Game Crashes on Startup with Patcher (Sk1er), Replay Mod, and 5zig.

### ISSUE THREAD

**Issue by APerson7** [5zig-reborn/The-5zig-Mod#108]
**What mod is causing it?**

This issue occurs with both Patcher (Sk1er) and The Replay Mod installed. 
I was unable to locate an up to date github for Patcher, but the Replay Mod github is here: https://github.com/ReplayMod/ReplayMod

The latest releases of all 3 mods were used, all on version 1.8.9:
Replay Mod Version 2.4.4: https://www.replaymod.com/download/
Patcher Version 1.3: https://sk1er.club/mods/patcher
5zig Version 3.14.0: https://5zigreborn.eu/downloads/

**Describe the bug**
The game crashes on startup, given that all 3 mods are installed. The following crash log appears: https://paste.ee/p/GYcWl

**To Reproduce**
1. Install Minecraft Forge (Version 1.8.9 - 11.15.1.2318, **not** 1.8.9 - 11.15.1.1722)
2. Move all 3 mods listed to mods folder
3. Attempt to launch the game
4. Crash before the Minecraft window even opens

**Expected behavior**
The game should launch and be playable, as these mods all work with 2/3 installed. However, this does not happen.

**Screenshots**

Proof that that these mods work without having all three:

Replay and 5zig:

![2020-09-19_21 38 53](https://user-images.githubusercontent.com/53496153/93704903-15d8f080-facd-11ea-8546-40c4d18907ec.png)

5zig and Patcher (difficult to show due to Patcher adding nothing to the menu. Both screenshots taken in same instance):

![2020-09-19_23 05 54](https://user-images.githubusercontent.com/53496153/93704999-63a22880-face-11ea-980c-234e4bbd0a23.png)

![2020-09-19_23 07 29](https://user-images.githubusercontent.com/53496153/93705002-6ac93680-face-11ea-98bc-5a6497db3f3d.png)

(also note that OpenEye was left over from when Replay Mod was installed, and did not affect the crash)

Replay and Patcher:

![2020-09-19_21 41 19](https://user-images.githubusercontent.com/53496153/93705102-5a658b80-facf-11ea-8669-03cb0214238c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5zig 3.14.0 (This may not be what goes here, please let me know if I'm wrong)

**Additional context**
This was tested on MultiMC, but the issue still occurs with the vanilla launcher. The latest version of forge for 1.8.9 was used. I believe that this is a Mixin issue, as most of the errors near the end of the crash log contain both this mod's name and a mixin version error. What is strange is that all 3 mods work just fine with only 2/3 installed. It is only when the third mod is added that the crash occurs.

This was tested on a brand new instance of Minecraft 1.8.9 with no extra mods (besides OpenEye, which managed to get installed somehow but luckily did not affect anything).

**Comment by APerson7** [comment]
I probably should have labeled this as a bug, but I'm not the best at using Github at the moment

**Comment by RoccoDev** [comment]
I think it also crashes with just Replay Mod, I'll take a look.

**Comment by U5B** [comment]
Someone in the Sk1er Discord said to use Replay Mod 2.4.1 with 5zig, as that I don't believe crashes it.

**Comment by U5B** [comment]
Did a quick search on the ReplayMod repository.
https://github.com/ReplayMod/ReplayMod/issues/184 says to rename the ReplayMod.jar so that it's mixins are loaded before 5zig's. That might fix the issue, however I don't know the exact issue.

**Comment by APerson7** [comment]
I'm a few days late, but I'll try that. Thanks
