### ISSUE TITLE
Incompbadible with Replay Mod

### ISSUE THREAD

**Issue by developmentPluto** [5zig-reborn/The-5zig-Mod#112]
Whilst using the latest version of 5zig it makes it crash when running replay mod alongside it

**Comment by JacksonChen666** [comment]
I do also have this issue. I have tried to find an already existing issue, and found https://github.com/5zig-reborn/The-5zig-Mod/issues/108#issuecomment-700204394 but I was able to get only replay mod 2.3.0 and 5zig b251 on 1.12.2 work. Hope this helps, or you can try to [binary search](https://youtu.be/2Rr2tW9zvRg) through the versions of replay mod if you're not on 1.12.2.
