### ISSUE TITLE
Player counter module counts everything

### ISSUE THREAD

**Issue by Lou5y** [5zig-reborn/The-5zig-Mod#117]
**Describe the bug**
Not sure if this is a bug or if it's intentional, but the player counter will just get everything in your Tab, and display that as the number of players.

**To Reproduce**
1. Log into server (tested on Hypixel and Hive) with the player counter module.
2. Hit Tab
3. If the Tab displays NPC's (Hive lobbies) or if it's completely custom (Hypixel Skyblock) then everything under it will be counted as a player.

**Expected behavior**
Everything in Tab will be counted as a player, even if they're not. 
You can see in Hypixel Skyblock with the custom Tab that displays account info and stuff, those are being counted as well. And the player count is showing as 153.

**Screenshots**
Hypixel Skyblock (or I think any server with a custom Tab): https://imgur.com/a/27zNNKj
Hive (or I think any server that shows NPC's): https://imgur.com/a/wOUowKR

**Desktop**
 - OS: Windows 10
 - Version 2004, Build 19041.572

**Additional context**
Username: Lou5y
Version 1.8.9

**Comment by RoccoDev** [comment]
Neither a bug, nor intentional. We simply can't distinguish (or we'd have to include workarounds for every server) these "fake" players, without resorting to only counting the players within the user's range.

**Comment by Lou5y** [comment]
Alright, thanks for responding.
