### ISSUE TITLE
JSON Messages are broken

### ISSUE THREAD

**Issue by Andre601** [5zig-reborn/The-5zig-Mod#122]
**Describe the bug**
While using 5Zig are none of the JSON messages working.
For example does a message, which has a link embedded into a message, no longer the prompt to open or copy the link when clicking it.
It instead does nothing.

I've made a quick test using the below /tellraw command to generate a message with hover message, open url, suggest command and execute command.
All except Hover message are NOT working which makes me assume that 5zig breaks the click event of the chat system (or something). This has been tested in singleplayer but also appears in multiplayer.

Command used:
```
/tellraw @a ["",{"text":"Hover Message","hoverEvent":{"action":"show_text","contents":"Hello!"}},{"text":"\n"},{"text":"Text with a Link","clickEvent":{"action":"open_url","value":"https://google.com"}},{"text":"\n"},{"text":"Suggest Command","clickEvent":{"action":"suggest_command","value":"/say hello"}},{"text":"\n"},{"text":"Execute Command","clickEvent":{"action":"run_command","value":"/say hello"}}]
```

**To Reproduce**
1. Have some JSON Message with a Click Action
2. Try to click the text

**Expected behavior**
Click Actions should be performed as usual.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.16.3 b242

**Additional context**
This has been reported on the Discord but I wanted to post it here too so that it won't get lost.

**Comment by RoccoDev** [comment]
Fixed in 038d25e91b5e1b3c6f99ebfbce89ac0bafd8137d.
