### ISSUE TITLE
Freeze at "Loading - Completing Minecraft initilization"

### ISSUE THREAD

**Issue by JitterDev** [5zig-reborn/The-5zig-Mod#155]
**Describe the bug**
Game does not reach main menu, freezes at 7/7 forge initilization
![image](https://user-images.githubusercontent.com/64605731/128109375-15724af7-1692-4e90-b4ec-4a10c4098c2a.png)

**To Reproduce**
1. Launch Minecraft
2. Wait
3. see freeze

**Expected behavior**
Game to launch correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/64605731/128109403-c9720f49-e087-4b51-af4c-8c37205f8321.png)

**Desktop (please complete the following information):**
 - OS: W10 Pro 20H2
 - Version b251 (latest as of now)
 - If built from source: N/A

**Additional context**
[latest.log](https://github.com/5zig-reborn/The-5zig-Mod/files/6928060/latest.log) latest.log
Forge version: `11.15.1.2318` (latest as of now)

**Comment by waterswimmer111** [comment]
Cannot reproduce. The 5zig jar is the only file of any kind in my mod folder, and the game boots perfectly fine.

**OS**: W10 Pro 20H2
**Mod version:** b251
**Forge version:** 1.8.9 - 11.15.1.2318

Maybe try removing all of your mods, checking if 5zig runs, and if it does, slowly add your mods back in one by one and see if the game crashes with any of them. Be sure to also remove any other mods you have in your mod folder, not just version-specific ones (not sure if this is necessary, I am not super experienced with forge).

**Comment by JitterDev** [comment]
@waterswimmer111 there are no other mods in the folder. Only 5zig.

**Comment by JitterDev** [comment]
No longer freezes
