### ISSUE TITLE
Can't clone due to inaccessible git submodules

### ISSUE THREAD

**Issue by zortax** [5zig-reborn/The-5zig-Mod#2]
:–(

**Comment by RoccoDev** [comment]
Fixed!

(blame Intellij...)

**Comment by zortax** [comment]
@RoccoDev could you maybe push your IntelliJ project files to the repo? I don't really know how to set this up...

**Comment by RoccoDev** [comment]
@zortax Intellij's Gradle system should handle it automatically.
Could you join our Discord (https://discord.gg/3NCKvV4) so I can assist you further?
