### ISSUE TITLE
Cape not uploading

### ISSUE THREAD

**Issue by BigDaddyChet** [5zig-reborn/The-5zig-Mod#23]
Whenever I go to upload a custom cape, it doesn't take it, it just leaves the old one posted
It just does this
https://gyazo.com/4f06201419ef9517bc0de785ad4040cd

Edit:  After updating to 3.13.1 I now see that it says "Invalid Cape Size"

**Comment by RoccoDev** [comment]
Can you send the cape you're trying to upload?

**Comment by BigDaddyChet** [comment]
These are the capes, even the template I got off the discord says "Invalid cape size"
![CustomCapeTemplate](https://user-images.githubusercontent.com/20807296/78721344-595fe980-78f5-11ea-8d6d-f4151099dc24.png)
![SasukeCape](https://user-images.githubusercontent.com/20807296/78721345-59f88000-78f5-11ea-9722-0a2751780855.png)

**Comment by RoccoDev** [comment]
Looks like Discord's image compression is to blame, can you please try with this image?
![Customcape03](https://user-images.githubusercontent.com/13873938/78895056-74099e00-7a6e-11ea-8ee3-6cd96e87b7f6.png)

**Comment by BigDaddyChet** [comment]
That works, thank you!

**Comment by RoccoDev** [comment]
Thank you. Leaving this issue open until I post templates.

**Comment by RoccoDev** [comment]
Links will appear on next server restart.
