### ISSUE TITLE
ChatFilter suggestions (might add more later)

### ISSUE THREAD

**Issue by U5B** [5zig-reborn/The-5zig-Mod#26]
**Is your feature request related to a problem? Please describe.**
Suggestions for Chat Filter
**Describe the solution you'd like**
${username} for current username in ChatFilter, Text Macros and Auto Join
~
**Describe alternatives you've considered**
N/A

**Additional context**
will add more suggestions to this issue as this is all I have for now

**Comment by U5B** [comment]
Option to enable text shortcuts to be used in chat filters.

**Comment by RoccoDev** [comment]
Can this be closed?
