### ISSUE TITLE
Mixin 0.8 support (Forge 1.14+)

### ISSUE THREAD

**Issue by RoccoDev** [5zig-reborn/The-5zig-Mod#4]
Mixin 0.8 is now on public preview, and 5zig will have to be tested against it. 
This hopefully also brings Forge support to 1.13 and 1.14.

Related to #1 and #3. 

Expect testing and fixes in the upcoming days.

**Comment by WorkInProgress-Development** [comment]
Is there anything I might be able to do to help with this?

**Comment by RoccoDev** [comment]
Starting from 1.16, only Fabric will be supported.
