### ISSUE TITLE
1.15 Menu Issue

### ISSUE THREAD

**Issue by NotGeri** [5zig-reborn/The-5zig-Mod#40]
Hey. 
Recently, in 1.15 Mojang changed the way you escape menus. Now, if you hit ESC, you will not exit the entire menu all together, just go to the previous menu you were in. 
In 5zig at the moment, neither of these work. I can't use ESC to leave the menu at all. 

I am using the v3.13.1 build with 1.15.2 fabric. 
I also have these other modifications: 
![image](https://user-images.githubusercontent.com/46295973/79738920-ba2bf080-82fd-11ea-80e0-06b337c055e8.png)

**Comment by RoccoDev** [comment]
Fixed by 8bbb479
