### ISSUE TITLE
Word highlight is not working in "5Zig 1.15.2" and "Fabric 5Zig 1.15.2"

### ISSUE THREAD

**Issue by RoccoDev** [5zig-reborn/The-5zig-Mod#45]
Submitter: TopComp
Title

**Comment by RoccoDev** [comment]
ibu cnr v=3.13.1 (Cannot reproduce on latest master)

**Comment by U5B** [comment]
ibu cnr v=3.13.1 (Cannot reproduce, however full message is highlighted)
