### ISSUE TITLE
FPS not working on 1.15.

### ISSUE THREAD

**Issue by JSR-Gaming-x** [5zig-reborn/The-5zig-Mod#47]
**Describe the bug**
FPS doesn't work. This is not an issue with Optifine's fps counter or f3. I do not have this issue with 5zig reborn 1.14.

**To Reproduce**
1. Install 5zig as its own version.
2. Add fps module.
3. Use eyes.

**Expected behavior**
FPS is stuck at 0 and flashes.

**Screenshots**
https://gyazo.com/49e8832d05d77384a220170090a605db

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04]
 - Version [e.g. 3.26.x]
 - If built from source: Commit Hash

**Additional context**

**Comment by Motschen** [comment]
ibu cnr v=3.13.0 I cannot reproduce the issue. This also is the case with 3.13.1.

**Comment by Motschen** [comment]
![2020-04-29_22 45 10](https://user-images.githubusercontent.com/49783724/80645299-35fb0b00-8a6b-11ea-8d90-ca8311cb6292.png)

**Comment by U5B** [comment]
ibu cnr v=3.13.1 Cannot reproduce on either 3.13.0 or 3.13.1

**Comment by U5B** [comment]
nevermind, found the issue
for some reason, if you toggle Precise FPS Counter off, it does as the bug says

**Comment by U5B** [comment]
![image](https://user-images.githubusercontent.com/56985400/80655295-24960c80-8a33-11ea-8c97-02c9e9195b3d.png)
Top is Precise FPS Counter off.
Bottom is Precise FPS Counter on.
