### ISSUE TITLE
[Mod Compat] KAMI 

### ISSUE THREAD

**Issue by dominikaaaa** [5zig-reborn/The-5zig-Mod#49]
**What mod is causing it?**

https://github.com/zeroeightysix/KAMI

**Does the mod load?**

Nope (full crash)

**Does 5zig load?**

Nope

**Which features of the mod don't work?**

None

**Which features of 5zig don't work?**

None

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Tested on Windows 10 and Arch Linux
 - Version: 3.13.0

**Additional context**

Log: https://pastebin.com/nG4H4fz7

The original 5zig author said he was working in it right before the project died, the issue can be found here: https://github.com/5zig/The-5zig-Mod-Docs/issues/32

Issue in KAMI's repo: https://github.com/zeroeightysix/KAMI/issues/31

**Comment by Motschen** [comment]
ibu cr v=3.13.0 also crashes with newest deployment (3.13.1), crashes right at the 7/7 state of mod loading

**Comment by dominikaaaa** [comment]
This has been an issue for like 2 years and I forgot to follow up on it because the original 5zig project went completely inactive, but yea that describes exactly it.

**Comment by RoccoDev** [comment]
Fixed with that commit. If any other compatibility issues arise with this mod, feel free to repoen.

**Comment by dominikaaaa** [comment]
Thank you, that was fast!
