### ISSUE TITLE
1.13.2 Crash when removing last element from GuiList

### ISSUE THREAD

**Issue by CWO333** [5zig-reborn/The-5zig-Mod#5]
Crash when removing an item or module from Customize Display.

To reproduce:
Go to Customize Display
Click Add Module
Immediately attempt to delete the new module

Using the 1.13.2 binary from this link:
[https://github.com/5zig-reborn/deployments/commit/001156099ff27eb3fc73648d2d78c068745f51a](https://github.com/5zig-reborn/deployments/commit/001156099ff27eb3fc73648d2d78c068745f51aa)

Only other mod installed is Optifine 1.13.2_HD_U_E7

>  ---- Minecraft Crash Report ----
> // Don't be sad, have a hug! <3
> 
> Time: 9/18/19 7:15 AM
> Description: mouseClicked event handler
> 
> java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.get(ArrayList.java:429)
> 	at GuiList.getHoverItem(GuiList.java:682)
> 	at GuiList.mouseClicked(GuiList.java:368)
> 	at eu.the5zig.mod.gui.Gui.mouseClicked0(Gui.java:313)
> 	at GuiHandle.mouseClicked(GuiHandle.java:112)
> 	at cfv.b(SourceFile:83)
> 	at cfv$$Lambda$1012/1375168324.run(Unknown Source)
> 	at ckd.a(SourceFile:430)
> 	at cfv.a(SourceFile:83)
> 	at cfv$$Lambda$830/768894611.invoke(Unknown Source)
> 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
> 	at org.lwjgl.system.JNI.invokeV(Native Method)
> 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
> 	at cgd.a(MainWindow.java:458)
> 	at cft.c(SourceFile:875)
> 	at cft.a(SourceFile:395)
> 	at net.minecraft.client.main.Main.main(SourceFile:144)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.get(ArrayList.java:429)
> 	at GuiList.getHoverItem(GuiList.java:682)
> 	at GuiList.mouseClicked(GuiList.java:368)
> 	at eu.the5zig.mod.gui.Gui.mouseClicked0(Gui.java:313)
> 	at GuiHandle.mouseClicked(GuiHandle.java:112)
> 	at cfv.b(SourceFile:83)
> 	at cfv$$Lambda$1012/1375168324.run(Unknown Source)
> 
> -- Affected screen --
> Details:
> 	Screen name: GuiHandle
> Stacktrace:
> 	at ckd.a(SourceFile:430)
> 	at cfv.a(SourceFile:83)
> 	at cfv$$Lambda$830/768894611.invoke(Unknown Source)
> 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
> 	at org.lwjgl.system.JNI.invokeV(Native Method)
> 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [ctj['CWO'/10548, l='MpServer', x=7414.93, y=6.37, z=4634.60]]
> 	Chunk stats: MultiplayerChunkCache: 81, 81
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: {}
> 	Level spawn location: World: (7424,6,4612), Chunk: (at 0,0,4 in 464,288; contains blocks 7424,0,4608 to 7439,255,4623), Region: (14,9; contains chunks 448,288 to 479,319, blocks 7168,0,4608 to 7679,255,5119)
> 	Level time: 1603 game time, 171995349 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> 	Forced entities: 14 total; [ann['Skeleton'/647457, l='MpServer', x=7381.50, y=40.00, z=4608.50], amt['Creeper'/647456, l='MpServer', x=7381.50, y=25.00, z=4629.50], anw['Zombie'/647459, l='MpServer', x=7383.50, y=21.00, z=4604.50], amt['Creeper'/647458, l='MpServer', x=7384.50, y=21.00, z=4605.50], ajt['Cow'/647449, l='MpServer', x=7412.71, y=6.00, z=4629.07], ajt['Cow'/647448, l='MpServer', x=7413.92, y=6.00, z=4629.07], ajt['Cow'/647451, l='MpServer', x=7413.64, y=6.00, z=4632.21], ajt['Cow'/647450, l='MpServer', x=7409.45, y=6.00, z=4632.46], ajt['Cow'/647453, l='MpServer', x=7411.23, y=6.00, z=4629.90], ajt['Cow'/647452, l='MpServer', x=7413.92, y=6.00, z=4631.13], ajt['Cow'/647455, l='MpServer', x=7409.45, y=6.00, z=4633.60], ctj['CWO'/10548, l='MpServer', x=7414.93, y=6.37, z=4634.60], ajt['Cow'/647454, l='MpServer', x=7413.02, y=6.00, z=4630.44], ajt['Cow'/647447, l='MpServer', x=7411.98, y=6.00, z=4630.94]]
> 	Retry entities: 0 total; []
> 	Server brand: Waterfall (git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290) <- Paper
> 	Server type: Non-integrated multiplayer server
> Stacktrace:
> 	at crg.a(WorldClient.java:576)
> 	at cft.b(SourceFile:1815)
> 	at cft.a(SourceFile:403)
> 	at net.minecraft.client.main.Main.main(SourceFile:144)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.13.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 567673192 bytes (541 MB) / 2088071168 bytes (1991 MB) up to 4207738880 bytes (4012 MB)
> 	JVM Flags: 25 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -Xms2G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048M -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ParallelGCThreads=10
> 	Launched Version: 1.13.2
> 	LWJGL: 3.1.6 build 14
> 	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.30, NVIDIA Corporation
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Very likely; Jar signature invalidated
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
>

**Comment by RoccoDev** [comment]
Can reproduce; happens when deleting the last module in the list.
Will work on a fix, thank you.
