### ISSUE TITLE
[Mod Compat] Baritone

### ISSUE THREAD

**Issue by U5B** [5zig-reborn/The-5zig-Mod#50]
**What mod is causing it?**
https://github.com/cabaletta/baritone

**Does the mod load?**
Yes
**Does 5zig load?**
Yes
**Which features of the mod don't work?**
ChatControl (Baritone's commands)
**Which features of 5zig don't work?**
Anything involving chat (Chat Filter, Text Shortcuts, Chat Macros, Auto Join Text)
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Minecraft Version 1.12.2
~ 5zig Version 3.13.1/3.13.0

**Additional context**
5zig is overwriting something with chat in Baritone. OG 5zig (3.12.5) did not have this issue with Baritone.

**Comment by U5B** [comment]
That commit fixed the issue with sending commands for Baritone. However, rfiltering chat messages using the Chat Filter seemed to stop working.

On the other hand, Word Highlight seems to work.

**Comment by RoccoDev** [comment]
Everything should be good now.
