### ISSUE TITLE
Ping Is Inaccurate

### ISSUE THREAD

**Issue by Bodopod** [5zig-reborn/The-5zig-Mod#54]
The ping always displays as 1 on servers.

![5zig Reborn Ping is Broken](https://user-images.githubusercontent.com/61366980/80929812-cc794600-8d63-11ea-9f86-30f768446839.png)

Most of the time, this happens on Hypixel.

**Comment by RoccoDev** [comment]
Unfortunately, this is something on Hypixel's end.  
See https://hypixel.net/threads/ping-bug.2454465/

**Comment by Bodopod** [comment]
Alright, thanks anyway.
