### ISSUE TITLE
ping value cannot be seen in tablist

### ISSUE THREAD

**Issue by mihapain1** [5zig-reborn/The-5zig-Mod#6]
To reproduce:
1. join server
2. press tab
* **Current behaviour**: 
![2019-09-18_19 09 24](https://user-images.githubusercontent.com/38764610/65165925-67791600-da48-11e9-8c22-9727e8bfa359.png)
![2019-09-18_19 09 24](https://user-images.githubusercontent.com/38764610/65166670-d3a84980-da49-11e9-907c-6d4c06c9fc6a.png)

**Expected behavior**
![2019-09-18_20 28 31](https://user-images.githubusercontent.com/38764610/65171223-09056500-da53-11e9-8d25-3cd23d64d0d7.png)

Display : 1920x1080 
GUI Scale: normal

**Comment by RoccoDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ping value error (Locale issue?)](https://trello.com/c/Pa2MfE4p/2-ping-value-error-locale-issue)
