### ISSUE TITLE
Add words to be pinged for in chat

### ISSUE THREAD

**Issue by iSneaky** [5zig-reborn/The-5zig-Mod#69]
**Describe the solution you'd like**
Would love to see some form of addition where users can add words they want to be alerted for in chat, when that word is spoken in chat by a user, the mod would send an audible ping noise to alert you of the message.

**Comment by U5B** [comment]
Already a feature.

Use 5zig's chat filter to play sounds.
![image](https://user-images.githubusercontent.com/56985400/82126155-a2f6ec00-975f-11ea-984d-255d62c9c2ea.png)

**Comment by iSneaky** [comment]
Great, thanks for that, I did look at the chat filter but I thought it was just for blocking messages in chat, thanks for the help. :)
