### ISSUE TITLE
crash when clicking "Plugins" button 

### ISSUE THREAD

**Issue by mihapain1** [5zig-reborn/The-5zig-Mod#7]
crash-report: 
[crash-2019-09-18_19.32.51-client.txt](https://github.com/5zig-reborn/The-5zig-Mod/files/3627445/crash-2019-09-18_19.32.51-client.txt)

other mods: 
Rift 1.0.4 
RiftTweakLoader 1.0.0
Optifine 1.13.2_HD_U_E7

**To Reproduce**
1. Go to 5zig mod menu
2. Click on "Plugins"
2. Crash

**Comment by RoccoDev** [comment]
The issue was caused by invalid plugins.
