### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by KermiDeLagyFrog** [5zig-reborn/The-5zig-Mod#79]
**Describe the bug**
Not a bug report but does anyone know how to get these to work
![Screenshot_1](https://user-images.githubusercontent.com/63331511/83362400-d16eec80-a345-11ea-91b7-f14578527d19.png)

**Comment by KermiDeLagyFrog** [comment]
its on hypixel btw

**Comment by RoccoDev** [comment]
Sorry for the late response, that module shows the current 5zig party members.  
The party feature allows you to have a 5zig group chat and join servers together.
