### ISSUE TITLE
can't start on Fabric 1.14.4

### ISSUE THREAD

**Issue by mihapain1** [5zig-reborn/The-5zig-Mod#9]
logs: [log.txt](https://github.com/5zig-reborn/The-5zig-Mod/files/4275660/log.txt)

mods:
   5zig-Fabric-Installer-1.0.2
   5zig-Reborn-1.14.4-3.13.0
 fabric 0.7.8+build.186
   fabric-api-0.4.2+build.246-1.14
   modmenu-1.7.16.1.14.4+build.128
   optifabric-0.7.1
   OptiFine_1.14.4_HD_U_F5

**Comment by roccodev** [comment]
Thanks.
Currently, if you plan on using fabric, you need to use version 0.6.2 to patch the file, after that you can switch to latest.
Once we release we'll provide pre-built Fabric jars in the downloads.
